config/routes.rb
Rails.application.routes.draw do
  root to: 'projects#index'
  devise_for :admins, path_names: { sign_up: 'secret_passage' }
  devise_for :users
  resources :projects
  get 'tags/:tag', to: 'projects#index', as: :tag
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  AVAILABILITY = [true, false]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :interns, class_name: 'User'
end

app/models/project.rb
class Project < ActiveRecord::Base
  MENTOR_ROLE = ['Code Reviewer', 'Pair Programmer', 'Client']
  PROJECT_LEVEL = ['Beginner', 'Intermediate', 'Advanced']

  belongs_to :intern, class_name: 'User', foreign_key: 'user_id'
  has_many :taggings
  has_many :tags, through: :taggings

  def all_tags=(names)
    self.tags = names.split(',').map do |t|
      Tag.where(name: t.downcase.strip).first_or_create!
    end
  end

  def all_tags
    tags.map(&:name).join(', ')
  end

  def self.tagged_with(name)
    Tag.find_by!(name: name).projects
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :projects, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :project
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects, dependent: :destroy
  belongs_to :mentor, class_name: 'Admin', foreign_key: 'mentor_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << [:github_account, :twitter_account, :mentor_id, :name, :availability]
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :admin_or_project_owner!, only: [:edit, :update, :destroy]

  def index
    if params[:tag]
      @projects = Project.tagged_with(params[:tag])
    else
      @projects = Project.all
    end
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = current_user.projects.new(project_params)

    respond_to do |format|
      if @project.save
        Notifier.new_project(@project).deliver
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
    end
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :github_url, :mentor_role, :user_id, :description, :project_level, :all_tags)
    end

    def admin_or_project_owner!
      if admin_signed_in?
      elsif
        @project.user_id == current_user.id
      else
        redirect_to root_path
        flash[:alert] = 'You do not have enough permission to do this'
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box radius <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Internbox', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul class="right">
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? %>
  <li class='active'><%= link_to 'New Project', new_project_path %></li>
  <li><%= link_to "#{current_user.email}" %></li>
  <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
  <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
<% elsif admin_signed_in? %>
  <li><%= link_to "#{current_admin.email} (Admin)" %></li>
  <li><%= link_to 'Edit Profile', edit_admin_registration_path %></li>
  <li><%= link_to 'Logout', destroy_admin_session_path, method: :delete %></li>
<% else %>
  <li class="active"><%= link_to 'Admin', new_admin_session_path %></li>
  <li><%= link_to 'Login', new_user_session_path %></li>
  <li class='active'><%= link_to 'Sign Up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Internbox" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Internbox" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <div class="row">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/notifier/new_project.text.erb
Hello <%= @mentor.name %>!
==========================

Your intern <%= @user.name %> (<%= @user.email %>) has created a new project.

Please help him/her as a <%= @project.mentor_role %>.

Take notice that this project level is <%= @project.project_level %>.

You can view the project's details at:

1) <%= project_url(@project) %>
2) <%= @project.github_url %>

Keep in touch with <%= @user.name %> at:

1) Github as: https://github.com/<%= @user.github_account %>
2) Twitter as: https://twitter.com/<%= @user.twitter_account %>

Happy mentoring <%= @mentor.name %>! Be kind to one another.

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Project Name' %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :github_url, 'Github' %><br>
    <%= f.text_field :github_url %>
  </div>

  <div class="field">
    <%= f.label :project_level, 'Project Level' %><br>
    <%= f.select :project_level,
        Project::PROJECT_LEVEL,
        {} %>
  </div>

  <div class="field">
    <%= f.label :mentor_role, 'Mentor Role' %><br>
    <%= f.select :mentor_role,
        Project::MENTOR_ROLE,
        {} %>
  </div>

  <div class="field">
    <%= f.label :all_tags, 'Tags (separate by comma)' %><br>
    <%= f.text_field :all_tags %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h3>All Projects</h3>

<%= div_for @projects, class: 'large-3 columns panel callout radius ' do |project| %>
  <p>
    <strong>Name</strong>
    <%= link_to "#{project.name}", project_path(project) %>
  </p>

  <p>
    <strong>Github</strong>
    <%= link_to project.github_url, project.github_url %>
  </p>

  <p>
    <strong>Intern</strong>
    <%= project.intern.name %>
  </p>

  <p>
    <strong>Mentor</strong>
    <%= project.intern.mentor.name %>
  </p>

  <p>
    <strong>Level</strong>
    <%= project.project_level %>
  </p>

  <p>
    <strong>Tags:</strong>
    <%= raw project.tags.map { |t| raw link_to t.name, tag_path(t.name) }.join(', ') %>
  </p>

  <%= link_to 'Details', project_path(project), class: 'button tiny radius success' %>
<% end %>

app/views/projects/new.html.erb
<div class="large-6 columns">
<h3>New project</h3>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>
</div>

app/views/projects/show.html.erb
<div class="large-centered columns panel radius">
  <p>
    <strong>Name:</strong>
    <%= @project.name %>
  </p>

  <p>
    <strong>Github:</strong>
    <%= link_to @project.github_url, @project.github_url %>
  </p>

  <p>
    <strong>Level:</strong>
    <%= @project.project_level %>
  </p>

  <p>
    <strong>Intern:</strong>
    <%= @project.intern.name %>
  </p>

  <p>
    <strong>Mentor:</strong>
    <%= @project.intern.mentor.name %>
  </p>

  <p>
    <strong>Mentor Role:</strong>
    <%= @project.mentor_role %>
  </p>

  <p class="tags">
    <strong>Tags:</strong>
    <%= raw @project.tags.map { |t| raw link_to t.name, tag_path(t.name) }.join(', ') %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @project.description %>
  </p>

  <%= link_to 'Back', projects_path, class: 'button tiny success radius' %>
  <% if admin_signed_in? || user_signed_in? %>
    <%= link_to 'Edit', edit_project_path(@project), class: 'button tiny success radius' %>
    <%= link_to 'Destroy', @project, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button tiny alert radius' %>
  <% end %>
</div>